config/routes.rb
Rails.application.routes.draw do
  get 'inventory_shoppings/index'
  resources :foods
  devise_for :users
  get '/public_recipes', to: 'recipes#public'

  root "users#index"

  resources :users

  resources :recipes do
    resources :shopping_lists
    resources :recipe_foods
  end

  # inventories

  resources :inventories do
    resources :inventory_foods, only: %i[ create destroy new]
  end

  get '/shopping_list', to: 'inventory_shoppings#index', as: :shopping
  get '/shopping_list?recipe_id=:id&inventory_id=:id', to: 'inventory_shoppings#index', as: :inventory_shopping_list

end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :shopping_lists

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :set_inventory, only: %i[show edit destroy]

  # GET /inventories or /inventories.json
  def index
    @inventories = Inventory.all
  end

  # GET /inventories/1 or /inventories/1.json
  def show
    @inventory_foods = InventoryFood.all.where(inventory_id: params[:id]).includes(:food)
  end

  # GET /inventories/new
  def new
    @inventory = Inventory.new
  end

  # GET /inventories/1/edit
  def edit; end

  # POST /inventories or /inventories.json
  def create
    @inventory = Inventory.new(inventory_params)
    @inventory.user_id = current_user.id

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_url }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventories/1 or /inventories/1.json
  def destroy
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_url, notice: 'Inventory was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_inventory
    @inventory = Inventory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def inventory_params
    params.require(:inventory).permit(:name, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_form.html.erb
<%= form_with(model: inventory) do |form| %>
  <% if inventory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>

      <ul>
        <% inventory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class: "form-label" %>
    <%= form.text_field :name, class: "form-control mb-3" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class: "form-label"  %>
    <%= form.text_area :description, class: "form-control mb-5" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inventories/_inventory.html.erb
<div class="" id="<%= dom_id inventory %>">
  <div>
    <%= link_to inventory_path(inventory), class: "text-decoration-none text-dark d-flex" do%>
      <p class="inventory-name">
        <%= inventory.name %>
      </p>

      <p class="inventory-description">
        <%= inventory.description %>
     </p>
    <% end %>
  </div>

</div>

app/views/inventories/_inventory_foods.html.erb
  <table class="table table-striped mt-5">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% inventory_foods.each do |inventory_food| %>
    <tr>
      <td><%= inventory_food.food.name %></td>
      <td><%= inventory_food.quantity %></td>
      <td>
        <% if can? :delete, inventory_food.inventory%>
            <%= button_to "Delete", inventory_inventory_food_path(inventory_food.inventory_id, inventory_food), method: :delete, class: "btn btn-danger btn-sm" %>
        <% else %>
            <%= button_to "Delete", inventory_inventory_food_path(inventory_food.inventory_id, inventory_food), method: :delete, class: "btn btn-danger btn-sm", disabled: true %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>

app/views/inventories/index.html.erb
<h1>Inventories</h1>

<div id="inventories" class="mt-2">
  <% @inventories.each do |inventory| %>
    <div class="inventory-display">
      <%= render inventory %>
      <% if can? :delete, inventory%>
        <%= button_to "REMOVE", inventory_path(inventory), method: :delete, class: "btn btn-danger btn-sm mt-2"%>
      <% end %>
    </div>
  <% end %>
</div>

<%= link_to "New inventory", new_inventory_path, class: "btn btn-success mt-4" %>

app/views/inventories/new.html.erb
<h1>New inventory</h1>

<%= render "form", inventory: @inventory %>

<br>

<div>
  <%= link_to "Back to inventories", inventories_path, class: "btn btn-success mt-4" %>
</div>

app/views/inventories/show.html.erb
<header class="inventory-food-header">
  <h2 class="text-center"><%= @inventory.name %></h2>
  <% if can? :create, @inventory %>
    <%= link_to "Add food",  new_inventory_inventory_food_path(@inventory), class: "btn btn-primary add-food float-end"%>
  <% end %>

</header>

 <%= render "inventories/inventory_foods", inventory_foods:@inventory_foods%>

<div>
  <%= link_to "Back to inventories", inventories_path, class: "btn btn-success mt-4" %>
</div>