config/routes.rb
Rails.application.routes.draw do
  get 'inventory_shoppings/index'
  resources :foods
  devise_for :users
  get '/public_recipes', to: 'recipes#public'

  root "users#index"

  resources :users

  resources :recipes do
    resources :shopping_lists
    resources :recipe_foods
  end

  # inventories

  resources :inventories do
    resources :inventory_foods, only: %i[ create destroy new]
  end

  get '/shopping_list', to: 'inventory_shoppings#index', as: :shopping
  get '/shopping_list?recipe_id=:id&inventory_id=:id', to: 'inventory_shoppings#index', as: :inventory_shopping_list

end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :shopping_lists

  validates :name, presence: true, length: { minimum: 3, maximum: 500 }
  validates :description, presence: true, length: { minimum: 3, maximum: 1000 }
  validates :preparation_time, presence: true, length: { minimum: 1, maximum: 15 }
  validates :cooking_time, presence: true, length: { minimum: 1, maximum: 15 }
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[public show]

  def index
    @recipes = Recipe.all.where(user_id: current_user.id).includes(:recipe_foods)
  end

  def show
    @recipe_foods = RecipeFood.all.where(recipe_id: params[:id]).includes(:food)
    @shopping_list =
      @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id
    if @recipe.save
      redirect_to recipes_url, notice: 'Recipe was successfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def public
    @recipes = Recipe.where(public: true).and(Recipe.where.not(user_id: current_user.id))
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    return unless @recipe.user.id == current_user.id

    @recipe.recipe_foods.destroy_all
    @recipe.destroy
    redirect_to recipes_url, notice: 'Recipe was successfully destroyed'
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, :preparation_time, :cooking_time, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_recipe_food.html.erb
  <table class="table table-striped mt-5">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Quantity</th>
      <th scope="col">Value</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% recipe_foods.each do |recipe_food| %>
    <tr>
      <td><%= recipe_food.food.name %></td>
      <td><%= recipe_food.quantity %></td>
      <td><%= recipe_food.food.price%></td>
      <td class="d-flex">
        <div class="me-3">
            <% if can? :edit, recipe_food.recipe %>
                <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food), method: :delete, class: "btn btn-danger btn-sm" %>
            <% else %>
                <%= button_to "Delete", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food), method: :delete, class: "btn btn-danger btn-sm", disabled: true%>
            <% end %>
        </div>
         <div>
            <% if can? :delete, recipe_food.recipe %>
                <%= link_to "Edit", edit_recipe_recipe_food_path(recipe_food.recipe_id, recipe_food), method: :edit, class: "btn btn-secondary btn-sm" %>
            <% end %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>

app/views/recipes/index.html.erb
  <div class="recipe-card">
    <% if @recipes.empty? %>
      <h2>No recipes yet</h2>
    <% end %>

    <% @recipes.each do |recipe| %>
      <div class="d-flex mb-3 align-items-center">
        <div class="w-25">
          <h3>
            <a href="/recipes/<%= recipe.id %>"> <%= recipe.name %></a>
          </h3>
          <% if can? :delete, recipe %>
            <%= button_to "Delete", recipe_path(recipe), method: :delete, class: "btn btn-danger" %>
          <% else %>
            <%= button_to "Delete", recipe_path(recipe), method: :delete, disabled: true, class: "btn btn-danger" %>
          <% end %>

        </div>
        <div class="ms-2">
          <%= recipe.description %></p>
        </div>
      </div>
    <% end %>

     <div class="new-recipe mt-4">
      <%=link_to new_recipe_path do %>
        <button class="btn btn-success">Add new recipe</button>
      <% end %>
     </div>
  </div>

app/views/recipes/new.html.erb
<div>
<h3> Add a new recipe </h3>
<%= form_with model: @recipe do |form| %>
    <div class="form-outline mb-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="form-outline mb-5">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control" %>
    </div>
    <div class="form-outline mb-5">
        <%= form.label :preparation_time %>
        <%= form.text_field :preparation_time, class: "form-control" %>
    </div>
    <div class="form-outline mb-5">
        <%= form.label :cooking_time %>
        <%= form.text_field :cooking_time, class: "form-control" %>
    </div>
    <div class="form-outline mb-5">
        <%= form.label :public %>
        <%= form.check_box :public %>
    </div>
    <div class="form-outline mb-5">
        <%= form.submit %>
    </div>
    <% end %>
</div>

app/views/recipes/public.html.erb
<h3 class="text-center">Recipes created by other users that are set to be public </h3>

<div>
<div>
    <% @recipes.each do |recipe| %>
        <% if recipe.public %>
            <div>
                <h3>
                <a href="/recipes/<%= recipe.id %>"> <%= recipe.name %></a>
                </h3>
                <p>Created By: <%= recipe.user.name %></p>
            </div>
            <div>
                <p> Total food items: <%= recipe.recipe_foods.count %></p>
            </div>
        <% end %>
    <% end %>
<div>
<p>
    <% if @recipes.empty? %>
        <span>No recipes added yet</span>
    <% end %>
    </p>
</div>
</div>

app/views/recipes/show.html.erb
<div>
    <h2 class="text-center"><%= @recipe.name %></h2>
    <div class="mb-4">
        <h5 class="mb-3"> Preparation time: <%= @recipe.preparation_time %> </h5>
        <h5 class="mb-3"> Cooking time: <%= @recipe.cooking_time %> </h5>
        <p>Steps: <%= @recipe.description %> </p>
    </div>
    <div class="d-flex justify-content-between pb-4 border-bottom border-dark">

        <%=link_to "Generate shopping list", new_recipe_shopping_list_path(@recipe), data: { turbo_frame: 'modal' }, class: "btn btn-success"%>

        <% if can? :destroy, @recipe %>
            <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe), class: "btn btn-primary add-food d-block"%>
        <% end %>
    </div>
    <div>
        <%= render "/recipes/recipe_food", recipe_foods:@recipe_foods%>
    </div>
</div>