config/routes.rb
Rails.application.routes.draw do
  get 'inventory_shoppings/index'
  resources :foods
  devise_for :users
  get '/public_recipes', to: 'recipes#public'

  root "users#index"

  resources :users

  resources :recipes do
    resources :shopping_lists
    resources :recipe_foods
  end

  # inventories

  resources :inventories do
    resources :inventory_foods, only: %i[ create destroy new]
  end

  get '/shopping_list', to: 'inventory_shoppings#index', as: :shopping
  get '/shopping_list?recipe_id=:id&inventory_id=:id', to: 'inventory_shoppings#index', as: :inventory_shopping_list

end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, foreign_key: 'food_id'
  has_many :inventory_foods, foreign_key: 'food_id'

  validates :name, presence: true, uniqueness: true
  validates :measurement_unit, presence: true
  validates :price, numericality: { greater_than: 0 }
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @foods = Food.all.includes(:inventory_foods, :recipe_foods)
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user = current_user

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.inventory_foods.destroy_all
    @food.recipe_foods.destroy_all
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <table class="table table-dark table-striped">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%=food.price %></td>
      <td><%= button_to "Destroy this food", @food, method: :delete %></td>
    </tr>
    </tbody>
  </table>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
  <% if food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form mt-5">
    <div>
      <%= form.label :name, class: "form-label fw-bold" %>
      <%= form.text_field :name, placeholder: "Apple", class: "form-control" %>
    </div>
  
    <div>
      <%= form.label :measurement_unit, class: "form-label fw-bold" %>
      <%= form.text_field :measurement_unit, placeholder: "grams", class: "form-control" %>
    </div>
  
    <div>
      <%= form.label :price,  class: "form-label fw-bold" %>
      <%= form.text_field :price, placeholder: "34.57",  class: "form-control" %>
    </div>
  
    <div>
      <%= form.submit "Add food", class: "btn btn-success fw-bold mt-2" %>
    </div>

    <button class="btn btn-secondary fw-bold align-self-start mt-5">
      <%= link_to "Back to foods", foods_path %>
    </button>
</div >
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Show this food", @food %> |
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/index.html.erb
<h1 class="text-center">List of Foods</h1>
<div class="container d-flex flex-column">
  <button class="align-self-end btn btn-primary new-food fw-bold"><%= link_to "Add food", new_food_path %></button>

  <table class="table table-dark table-striped mt-5">
    <thead>
    <tr>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Actions</th>
    </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <% if food.user == current_user %>
            <td><%= button_to "Delete", food, method: :delete, class: "btn btn-danger fw-bold" %></td>
          <% else %>
            <td><%= button_to "Delete", food, method: :delete, class: "btn btn-danger fw-bold", disabled: true %></td>
          <% end %>
        </tr>
      <% end %>
  </tbody>
  </table>

</div>

app/views/foods/new.html.erb
<h1 class="text-center">Add new food</h1>

<div class="container d-flex align-items-center flex-column justify-content-center mt-2">
  <%= render "form", food: @food %>
</div >

app/views/foods/show.html.erb
<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>