config/routes.rb
Rails.application.routes.draw do
  get 'inventory_shoppings/index'
  resources :foods
  devise_for :users
  get '/public_recipes', to: 'recipes#public'

  root "users#index"

  resources :users

  resources :recipes do
    resources :shopping_lists
    resources :recipe_foods
  end

  # inventories

  resources :inventories do
    resources :inventory_foods, only: %i[ create destroy new]
  end

  get '/shopping_list', to: 'inventory_shoppings#index', as: :shopping
  get '/shopping_list?recipe_id=:id&inventory_id=:id', to: 'inventory_shoppings#index', as: :inventory_shopping_list

end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :food
  belongs_to :recipe

  validates :quantity, presence: true, numericality: { only_integer: true }
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_food, only: %i[show edit update destroy]

  # GET /recipe_foods or /recipe_foods.json
  def index
    @recipe_foods = RecipeFood.all
  end

  # GET /recipe_foods/1 or /recipe_foods/1.json
  def show; end

  # GET /recipe_foods/new
  def new
    @all_foods = Food.all
    @recipe_food = RecipeFood.new
  end

  # GET /recipe_foods/1/edit
  def edit
    @all_foods = Food.all
  end

  # POST /recipe_foods or /recipe_foods.json
  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    recipe_id = params[:recipe_id]
    @recipe_food.recipe_id = recipe_id

    respond_to do |format|
      if @recipe_food.save
        format.html { redirect_to recipe_url(recipe_id), notice: 'Recipe food was successfully created.' }
      else
        format.html do
          rendirect_to new_recipe_recipe_food_url(recipe_id), status: :unprocessable_entity,
                                                              alert: 'Incomplete form submitted'
        end
      end
    end
  end

  # PATCH/PUT /recipe_foods/1 or /recipe_foods/1.json
  def update
    respond_to do |format|
      if @recipe_food.update(recipe_food_params)
        format.html { redirect_to recipe_url(@recipe_food.recipe_id), notice: 'Recipe food was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_foods/1 or /recipe_foods/1.json
  def destroy
    @recipe_food.destroy

    respond_to do |format|
      format.html { redirect_to recipe_url, notice: 'Recipe food was successfully destroyed.' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe_food
    @recipe_food = RecipeFood.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/views/recipe_foods/_edit_form.html.erb
<%= form_with model: recipe_food, url: recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.id), html: {method: "patch"} do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :Please_select_a_food_item_to_add, class: "d-block mb-2"%>
    <%= form.collection_select :food_id, all_foods, :id, :name, :prompt => true, class: "select-inventory-food w-75" %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity, class: "mt-2" %>
  </div>

  <div class="mt-4">
    <%= form.submit "Update Recipe Food" %>
  </div>
<% end %>

app/views/recipe_foods/_form.html.erb
<%= form_with(model: recipe_food, url: recipe_recipe_foods_path) do |form| %>
  <% if recipe_food.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe_food.errors.count, "error") %> prohibited this recipe_food from being saved:</h2>

      <ul>
        <% recipe_food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :Please_select_a_food_item_to_add, class: "d-block label-inv-food"%>
    <%= form.collection_select :food_id, all_foods, :id, :name, :prompt => true, class: "select-inventory-food" %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipe_foods/_recipe_food.html.erb
<div id="<%= dom_id recipe_food %>">
  <p>
    <strong>Quantity:</strong>
    <%= recipe_food.quantity %>
  </p>

  <p>
    <strong>Food:</strong>
    <%= recipe_food.food_id %>
  </p>

  <p>
    <strong>Recipe:</strong>
    <%= recipe_food.recipe_id %>
  </p>

</div>

app/views/recipe_foods/edit.html.erb
<h1>Editing recipe food</h1>

<%= render "edit_form", recipe_food: @recipe_food, all_foods: @all_foods %>

app/views/recipe_foods/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe foods</h1>

<div id="recipe_foods">
  <% @recipe_foods.each do |recipe_food| %>
    <%= render recipe_food %>
    <p>
      <%= link_to "Show this recipe food", recipe_food %>
    </p>
  <% end %>
</div>

<%= link_to "New recipe food", new_recipe_food_path %>

app/views/recipe_foods/new.html.erb
<h1>New recipe food</h1>

<%= render "form", recipe_food: @recipe_food, all_foods:@all_foods %>

<br>

app/views/recipe_foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @recipe_food %>

<div>
  <%= link_to "Edit this recipe food", edit_recipe_food_path(@recipe_food) %> |
  <%= link_to "Back to recipe foods", recipe_foods_path %>

  <%= button_to "Destroy this recipe food", @recipe_food, method: :delete %>
</div>